server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
        routes:
          - id: customer-service
            uri: lb://customer-service
            predicates:
              - Path=/customers/**
          - id: comunes-query-service
            uri: lb://comunes-query-service
            predicates:
              - Path=/comunes-query-service/**